{{- if .Values.createdb.enabled }}
{{- if .Values.createdb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "archivista.mysql.labels" . | nindent 4 }}
  name: {{ template "archivista.serviceAccountName.createdb" . }}
{{ include "archivista.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.createdb.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}