{{- if (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.mysql.secret.annotations }}
  annotations:
{{ toYaml .Values.mysql.secret.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "archivista.mysql.labels" . | nindent 4 }}
{{- if .Values.mysql.secret.labels }}
{{ toYaml .Values.mysql.secret.labels | indent 4 }}
{{- end }}
  name: {{ template "archivista.mysql.fullname" . }}
{{ include "archivista.namespace" . | indent 2 }}
type: Opaque
data:
  {{- if .Values.mysql.enabled -}}
  {{- if not (empty .Values.mysql.auth.rootPassword) }}
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ (include "archivista.randomSecret" (dict "secretName" (include "archivista.mysql.fullname" .) "key" "mysql-root-password" "context" $)) | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not (empty .Values.mysql.auth.password) }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ (include "archivista.randomSecret" (dict "secretName" (include "archivista.mysql.fullname" .) "key" "mysql-password" "context" $)) | b64enc | quote }}
  {{- end }}
  mysql-user: {{ .Values.mysql.auth.username | b64enc | quote }}
  mysql-database:  {{ (include "mysql.database" .) | b64enc | quote }}
{{- end }}