{{- if .Values.mysql.enabled -}}
{{- if .Values.mysql.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{- include "archivista.mysql.labels" . | nindent 4 }}
  name: {{ template "archivista.serviceAccountName.mysql" . }}
{{ include "archivista.namespace" . | indent 2 }}
  annotations:
    {{ toYaml .Values.mysql.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
